<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4UEO4TP" name="com.excel.excel.Testxl" tests="10" failures="0" timestamp="14 Feb 2022 12:45:12 GMT" time="23.995" errors="1">
  <testcase name="registration" time="2.773" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.547" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.585" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.468" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.904" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.728" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.489" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="2.675" classname="com.excel.excel.Testxl"/>
  <testcase name="registration" time="0.084" classname="com.excel.excel.Testxl">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.excel.excel.Testxl.registration(Testxl.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- registration -->
  <testcase name="registration" time="2.742" classname="com.excel.excel.Testxl"/>
</testsuite> <!-- com.excel.excel.Testxl -->
